/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <string.h>
#include <stdio.h>
#include "app_alarm.h"
#include "os_threads.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x02)
#define ID_CHECKBOX_1 (GUI_ID_USER + 0x03)
#define ID_CHECKBOX_2 (GUI_ID_USER + 0x04)
#define ID_CHECKBOX_3 (GUI_ID_USER + 0x05)
#define ID_CHECKBOX_4 (GUI_ID_USER + 0x06)
#define ID_CHECKBOX_5 (GUI_ID_USER + 0x07)
#define ID_CHECKBOX_6 (GUI_ID_USER + 0x08)
#define ID_LISTWHEEL_0 (GUI_ID_USER + 0x09)
#define ID_LISTWHEEL_1 (GUI_ID_USER + 0x0A)
#define ID_DROPDOWN_0 (GUI_ID_USER + 0x0B)
#define ID_SLIDER_0 (GUI_ID_USER + 0x0C)
#define ID_TEXT_1 (GUI_ID_USER + 0x0D)
#define ID_TEXT_2 (GUI_ID_USER + 0x0E)
#define ID_TEXT_3 (GUI_ID_USER + 0x0F)
#define ID_RADIO_0 (GUI_ID_USER + 0x10)
#define ID_CHECKBOX_7 (GUI_ID_USER + 0x11)
#define ID_BUTTON_0 (GUI_ID_USER + 0x12)
#define ID_BUTTON_1 (GUI_ID_USER + 0x13)
#define ID_LISTWHEEL_2 (GUI_ID_USER + 0x14)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern void ListWheelMoveToEffect(GUI_HWIN hItem, uint8_t pos);
extern U8 ListWheelSelectededEffect(GUI_HWIN hItem);
extern void ListWheelClickedEffect(GUI_HWIN hItem);
extern uint8_t  Alarm_Thread_Exist;


void MoveToAlarmWindow(WM_HWIN hWin);
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "AlarmWindow", ID_WINDOW_0, 0, 0, 480, 242, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 140, 3, 200, 30, 0, 0x64, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox1", ID_CHECKBOX_0, 20, 30, 60, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox2", ID_CHECKBOX_1, 20, 60, 60, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox3", ID_CHECKBOX_2, 20, 90, 60, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox4", ID_CHECKBOX_3, 20, 120, 60, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox5", ID_CHECKBOX_4, 20, 150, 60, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox6", ID_CHECKBOX_5, 20, 180, 60, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox7", ID_CHECKBOX_6, 20, 210, 60, 20, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_0, 75, 40, 40, 178, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_1, 125, 40, 40, 178, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 390, 30, 80, 21, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 233, 70, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 240, 40, 100, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 224, 85, 30, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 332, 85, 30, 20, 0, 0x64, 0 },
  { RADIO_CreateIndirect, "Radio", ID_RADIO_0, 253, 118, 80, 50, 0, 0x1e02, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_7, 248, 185, 96, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ButtonOn", ID_BUTTON_0, 380, 125, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ButtonOf", ID_BUTTON_1, 380, 185, 80, 40, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_2, 175, 40, 40, 178, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static char * _apHour[] = {
   "00","01", "02", "03", "04",
  "05", "06", "07", "08",
  "09", "10", "11", "12",
  "13", "14", "15", "16",
  "17", "18", "19", "20",
  "21", "22", "23", NULL
};

static char * _apMinute[] = {
  "00","01", "02", "03", "04",
  "05", "06", "07", "08",
  "09", "10", "11", "12",
  "13", "14", "15", "16",
  "17", "18", "19", "20",
  "21", "22", "23", "24",
  "25", "26", "27", "28",
  "29", "30", "31", "32",
  "33", "34", "35", "36",
  "37", "38", "39", "40",
  "41", "42", "43", "44",
  "45", "46", "47", "48",
  "49", "50", "51", "52",
  "53", "54", "55", "56",
  "57", "58", "59", NULL
};

static int _OwnerDraw(const WIDGET_ITEM_DRAW_INFO * pDrawItemInfo)
{
  GUI_RECT aRect;

  switch (pDrawItemInfo->Cmd) {
  case WIDGET_ITEM_DRAW_OVERLAY:
    aRect.x0 = pDrawItemInfo->x0;
    aRect.x1 = pDrawItemInfo->x1;
    aRect.y1 = pDrawItemInfo->y1;
    GUI_SetColor(GUI_GRAY_E7);
    GUI_DrawLine(aRect.x0, (aRect.y1-19-16)/2, aRect.x1, (aRect.y1-19-16)/2);
    GUI_DrawLine(aRect.x0, (aRect.y1+19+16)/2, aRect.x1, (aRect.y1+19+16)/2);
    break;
  default:
    return LISTWHEEL_OwnerDraw(pDrawItemInfo);
  }
  return 0;
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
  U8      alarmIndex = DROPDOWN_GetSel(hItem);
  alarm_t* pAlarm = &(app_alarm_arr[alarmIndex]); 
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'AlarmWindow'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00E3F5D8));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
    TEXT_SetText(hItem, "Alarm Settings");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF0000));
    //
    // Initialization of 'Checkbox1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "Sun");
    //
    // Initialization of 'Checkbox2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
    CHECKBOX_SetText(hItem, "Mon");
    //
    // Initialization of 'Checkbox3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2);
    CHECKBOX_SetText(hItem, "Tue");
    //
    // Initialization of 'Checkbox4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3);
    CHECKBOX_SetText(hItem, "Wed");
    //
    // Initialization of 'Checkbox5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4);
    CHECKBOX_SetText(hItem, "Thu");
    //
    // Initialization of 'Checkbox6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5);
    CHECKBOX_SetText(hItem, "Fri");
    //
    // Initialization of 'Checkbox7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_6);
    CHECKBOX_SetText(hItem, "Sat");
    //
    // Initialization of 'Dropdown'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_AddString(hItem, "Alarm1");
    DROPDOWN_SetFont(hItem, GUI_FONT_16B_ASCII);
    DROPDOWN_AddString(hItem, "Alarm2");
    DROPDOWN_AddString(hItem, "Alarm3");
    DROPDOWN_AddString(hItem, "Alarm4");
    DROPDOWN_AddString(hItem, "Alarm5");
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_13HB_ASCII);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00800040));
    TEXT_SetText(hItem, "Alarm Volume");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetText(hItem, "10");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "100");
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Radio'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
    RADIO_SetText(hItem, "Periodic", 1);
    RADIO_SetFont(hItem, GUI_FONT_13HB_ASCII);
    RADIO_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    RADIO_SetText(hItem, "Once", 0);
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_7);
    CHECKBOX_SetText(hItem, "Light Effect");
    CHECKBOX_SetFont(hItem, GUI_FONT_16_ASCII);
    //
    // Initialization of 'ButtonOn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    BUTTON_SetText(hItem, "Turn on");
    //
    // Initialization of 'ButtonOf'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    BUTTON_SetText(hItem, "Turn off");
    // USER START (Optionally insert additional code for further widget initialization)
    memset(app_alarm_arr, 0, sizeof(alarm_t) * APP_ALARM_NUM);

    for (int i = 0; i < 2; i++)
    {
      hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0 + i);
      LISTWHEEL_SetLineHeight(hItem, 34);
      LISTWHEEL_SetSnapPosition(hItem, (178 - 34) / 2);
      LISTWHEEL_SetFont(hItem, GUI_FONT_16B_ASCII);
      LISTWHEEL_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
      LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_UNSEL, 0x191919);
      LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x007dfe);
      LISTWHEEL_SetDeceleration(hItem, 35);
      LISTWHEEL_SetOwnerDraw(hItem, _OwnerDraw);
      LISTWHEEL_SetSel(hItem, 0);
    }
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
    LISTWHEEL_SetLineHeight(hItem, 34);
    LISTWHEEL_SetSnapPosition(hItem, (178 - 34) / 2);
    LISTWHEEL_SetFont(hItem, GUI_FONT_16B_ASCII);
    LISTWHEEL_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_UNSEL, 0x191919);
    LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x007dfe);
    LISTWHEEL_SetDeceleration(hItem, 35);
    LISTWHEEL_SetOwnerDraw(hItem, _OwnerDraw);
    LISTWHEEL_SetSel(hItem, 0);

    LISTWHEEL_SetText(WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0), _apHour);
    LISTWHEEL_SetText(WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1), _apMinute);
    LISTWHEEL_SetText(WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2), _apMinute);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
    SLIDER_SetRange(hItem, 10, 100);
    SLIDER_SetNumTicks(hItem, 9);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_CHECKBOX_0: // Notifications sent by 'Checkbox1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, Id);
        if(CHECKBOX_GetState(hItem))
          pAlarm->weekday |= 1 << ((Id) - ID_CHECKBOX_0);
        else
          pAlarm->weekday &= ~(1 << ((Id) - ID_CHECKBOX_0));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_1: // Notifications sent by 'Checkbox2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, Id);
        if(CHECKBOX_GetState(hItem))
          pAlarm->weekday |= 1 << ((Id) - ID_CHECKBOX_0);
        else
          pAlarm->weekday &= ~(1 << ((Id) - ID_CHECKBOX_0));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_2: // Notifications sent by 'Checkbox3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, Id);
        if(CHECKBOX_GetState(hItem))
          pAlarm->weekday |= 1 << ((Id) - ID_CHECKBOX_0);
        else
          pAlarm->weekday &= ~(1 << ((Id) - ID_CHECKBOX_0));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_3: // Notifications sent by 'Checkbox4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, Id);
        if(CHECKBOX_GetState(hItem))
          pAlarm->weekday |= 1 << ((Id) - ID_CHECKBOX_0);
        else
          pAlarm->weekday &= ~(1 << ((Id) - ID_CHECKBOX_0));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_4: // Notifications sent by 'Checkbox5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, Id);
        if(CHECKBOX_GetState(hItem))
          pAlarm->weekday |= 1 << ((Id) - ID_CHECKBOX_0);
        else
          pAlarm->weekday &= ~(1 << ((Id) - ID_CHECKBOX_0));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_5: // Notifications sent by 'Checkbox6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, Id);
        if(CHECKBOX_GetState(hItem))
          pAlarm->weekday |= 1 << ((Id) - ID_CHECKBOX_0);
        else
          pAlarm->weekday &= ~(1 << ((Id) - ID_CHECKBOX_0));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_6: // Notifications sent by 'Checkbox7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, Id);
        if(CHECKBOX_GetState(hItem))
          pAlarm->weekday |= 1 << ((Id) - ID_CHECKBOX_0);
        else
          pAlarm->weekday &= ~(1 << ((Id) - ID_CHECKBOX_0));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_0: // Notifications sent by 'Listwheel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        ListWheelClickedEffect(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        pAlarm->hour = ListWheelSelectededEffect(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_1: // Notifications sent by 'Listwheel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        ListWheelClickedEffect(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        pAlarm->minute = ListWheelSelectededEffect(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_0: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        pAlarm = &(app_alarm_arr[DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id))]);

        if(alarm_isEnabled(pAlarm)){
          WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0));
          WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
        }
        else{
          WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
          WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0));
        }

        hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
        RADIO_SetValue(hItem, alarm_isPeriodic(pAlarm) == 0 ? 0 : 1);

        if (alarm_isPeriodic(pAlarm))
        {
          for (int i = 0; i < 7; i++)
          {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0 + i);
            WM_EnableWindow(hItem);
          }
        }
        else
        {
          for (int i = 0; i < 7; i++)
          {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0 + i);
            CHECKBOX_Uncheck(hItem);
            WM_DisableWindow(hItem);
          }
        }

        for (int i = 0; i < 7; i++)
        {
          hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0 + i);
          if (pAlarm->weekday & (APP_ALARM_SUNDAY << i))
            CHECKBOX_Check(hItem);
          else
            CHECKBOX_Uncheck(hItem);
        }

        hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_7);
        if (alarm_isLightEffect(pAlarm))
          CHECKBOX_Check(hItem);
        else
          CHECKBOX_Uncheck(hItem);

        ListWheelMoveToEffect(WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0), pAlarm->hour);
        ListWheelMoveToEffect(WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1), pAlarm->minute);
        ListWheelMoveToEffect(WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2), pAlarm->second);

        if(pAlarm->alarmVolume < 10 || pAlarm->alarmVolume > 100)
          pAlarm->alarmVolume = 10;
        SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0), pAlarm->alarmVolume);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, Id);
        pAlarm->alarmVolume = SLIDER_GetValue(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_0: // Notifications sent by 'Radio'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, Id);
        if(RADIO_GetValue(hItem)){
          pAlarm->property |= APP_ALARM_PERIODIC;
          for(int i = 0; i < 7; i++){
            hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0 + i);
            WM_EnableWindow(hItem);
          }
        }
        else{
          pAlarm->property &= ~APP_ALARM_PERIODIC;
          pAlarm->weekday = 0;
          for(int i = 0; i < 7; i++){
            hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0 + i);
            CHECKBOX_Uncheck(hItem);
            WM_DisableWindow(hItem);
          }
        }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_7: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, Id);
        if(CHECKBOX_GetState(hItem))
          alarm_setLightEffect(pAlarm);
        else
          alarm_clearLightEffect(pAlarm);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'ButtonOn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        alarm_setEnabled(pAlarm);
        if(Alarm_Thread_Exist == 0)
          vAlarmTaskCreate();     // 启动闹钟线程
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, Id));
        WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'ButtonOf'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        alarm_clearEnabled(pAlarm);
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, Id));
        WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0));
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_2: // Notifications sent by 'Listwheel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        ListWheelClickedEffect(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        pAlarm->second = ListWheelSelectededEffect(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateAlarmWindow
*/
WM_HWIN CreateAlarmWindow(void);
WM_HWIN CreateAlarmWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
/**
 * @brief   完成跳转到 `ClockWindow` 的工作——更新一些控件
 * @param   WM_HWIN hWin
 * @return  void
 */
void MoveToAlarmWindow(WM_HWIN hWin)
{
  WM_HWIN hItem;

  // 通过设置 dropdown 触发 DROPDOWM 事件更新控件
  hItem = WM_GetDialogItem(hWin, ID_DROPDOWN_0);
  DROPDOWN_SetSel(hItem, (DROPDOWN_GetSel(hItem) + 1)%APP_ALARM_NUM);
  DROPDOWN_SetSel(hItem, (DROPDOWN_GetSel(hItem) + APP_ALARM_NUM - 1)%APP_ALARM_NUM);
}
// USER END

/*************************** End of file ****************************/
