/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "main.h"
#include "dialog_window.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0         (GUI_ID_USER + 0x00)
#define ID_TEXT_0         (GUI_ID_USER + 0x01)
#define ID_BUTTON_0         (GUI_ID_USER + 0x02)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static void ButtonEventProcess(WM_HWIN hWin);
extern void MoveToAlarmWindow(WM_HWIN hWin);


uint16_t       DIALOG_TOP_EXIST = 0;
WM_HWIN        hStayOnTopWindow;

static DIALOG_TYPE   dialog_type = 0;
static uint16_t      DIALOG_WINDOW_EXIST = 0;
static WM_HWIN       hAlarmDialog;


extern TIM_HandleTypeDef htim3;
extern TIM_HandleTypeDef htim5;
extern WM_HWIN           hAlarmWindow;
extern U16    Music_Play_On;              // 音乐播放中标志
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "AlarmDialog", ID_FRAMEWIN_0, 140, 55, 200, 150, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 2, 0, 184, 75, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 52, 82, 80, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'AlarmDialog'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetFont(hItem, GUI_FONT_20B_ASCII);
    FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x000000FF));
    FRAMEWIN_SetText(hItem, "Alarm");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    TEXT_SetText(hItem, "Alarm is on");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_13B_ASCII);
    BUTTON_SetText(hItem, "Close");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        ButtonEventProcess(pMsg->hWin);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateAlarmDialog
*/
WM_HWIN CreateAlarmDialog(void);
WM_HWIN CreateAlarmDialog(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// 一些 dialog_type 可能的取值


/**
 * @brief  显示一个提醒对话框
 * @param  char * title：对话框标题
 * @param  char * text：对话框说明文字
 * @param  uint16_t type：对话框类型
 * @retval None
 */
WM_HWIN CreateAlarmDialog_Self(char * title, char * text, DIALOG_TYPE type) {
  WM_HWIN hWin;

  if(DIALOG_WINDOW_EXIST == 1)
    ButtonEventProcess(hAlarmDialog);
  if(DIALOG_TOP_EXIST == 1)
    WM_SetStayOnTop(hStayOnTopWindow, 0);

  dialog_type = type;

  DIALOG_WINDOW_EXIST = 1;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  hAlarmDialog = hWin;
  FRAMEWIN_SetText(hWin, title);
  TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_0), text);

  WM_MakeModal(hWin);
  WM_SetStayOnTop(hWin, 1);
  return hWin;
}



static void ButtonEventProcess(WM_HWIN hWin)
{
  if(dialog_type & DIALOG_ALARM)
  {
    __HAL_TIM_SetCompare(&htim3, TIM_CHANNEL_2, 0);
    if(Music_Play_On)
      Music_Play_On = 0;
    else
      HAL_TIM_PWM_Stop(&htim5, TIM_CHANNEL_4);
    MoveToAlarmWindow(hAlarmWindow);
  }

  if(DIALOG_TOP_EXIST == 1){
    WM_SetStayOnTop(hStayOnTopWindow, 1);
    WM_MakeModal(hStayOnTopWindow);
  }


  DIALOG_WINDOW_EXIST = 0;
  GUI_EndDialog(hWin, 0);
}
// USER END

/*************************** End of file ****************************/
