/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "os_threads.h"
#include "cmsis_os.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_GRAPH_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_0 (GUI_ID_USER + 0x02)
#define ID_BUTTON_0 (GUI_ID_USER + 0x03)
#define ID_BUTTON_1 (GUI_ID_USER + 0x04)
#define ID_BUTTON_2 (GUI_ID_USER + 0x05)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x06)


// USER START (Optionally insert additional defines)
void MoveToAudioWindow(WM_HWIN hWin);
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
GRAPH_DATA_Handle hGraphData_AudioWindow;
extern uint16_t Audio_Record_OnOff;                 // 音调提取开启标志
extern uint16_t Audio_Record_Ready;                     // 音调提取完成标志
extern uint16_t Audio_Record_Replay;                // 音调重放标志
extern uint16_t audio_main_freq_index;
extern uint32_t  audio_record_buffer_len;
extern uint16_t Audio_Full_Record;

extern uint16_t Audio_Thread_Exist;
extern uint16_t Audio_Thread_Terminate;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "AudioWindow", ID_WINDOW_0, 0, 0, 480, 242, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 0, 40, 380, 202, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 200, 0, 80, 20, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Start", ID_BUTTON_0, 390, 40, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ReocrdButton", ID_BUTTON_1, 390, 145, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ReplayButton", ID_BUTTON_2, 390, 195, 80, 40, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 390, 109, 85, 25, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Graph'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    GRAPH_SetBorder(hItem, 0, 0, 0, 0);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
    TEXT_SetText(hItem, "Audio In");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF0000));
    //
    // Initialization of 'Start'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    BUTTON_SetText(hItem, "Start");
    //
    // Initialization of 'ReocrdButton'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    BUTTON_SetText(hItem, "Record");
    //
    // Initialization of 'ReplayButton'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    BUTTON_SetText(hItem, "Replay");
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "HiRes");
    CHECKBOX_SetTextColor(hItem, GUI_MAKE_COLOR(0x0000D7FF));
    CHECKBOX_SetFont(hItem, GUI_FONT_20B_ASCII);
    // USER START (Optionally insert additional code for further widget initialization)
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00E3F5D8));
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    GRAPH_SetColor(hItem, GUI_WHITE, GRAPH_CI_BK);
    GRAPH_SetBorder(hItem, 10, 10, 10, 10);
	  GRAPH_SetLineStyleH(hItem, GUI_LS_DOT);
	  GRAPH_SetLineStyleV(hItem, GUI_LS_DOT);
	  /* 创建数据对象 */
	  hGraphData_AudioWindow = GRAPH_DATA_YT_Create(GUI_RED, 360, 0, 0);
	  GRAPH_AttachData(hItem, hGraphData_AudioWindow);

    WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
    WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2));
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Start'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        vAudioTaskCreate();
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, Id));
        WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'ReocrdButton'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        if(Audio_Record_OnOff == 0)
        {
          Audio_Record_OnOff = 1;
          audio_main_freq_index = 0;
          audio_record_buffer_len = 0;
          Audio_Full_Record = CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0));

          hItem = WM_GetDialogItem(pMsg->hWin, Id);
          BUTTON_SetText(hItem, "Stop Rec");
          BUTTON_SetTextColor(hItem, 0, GUI_RED);
          WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2));
          WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0));

          WM_CreateTimer(pMsg->hWin, 0, 100, 0);        // 创建定时器
        }
        else if(Audio_Record_OnOff == 1)
        {
          Audio_Record_OnOff = 0;
          hItem = WM_GetDialogItem(pMsg->hWin, Id);
          BUTTON_SetText(hItem, "Record");
          BUTTON_SetTextColor(hItem, 0, GUI_BLACK);
          WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2));
          WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0));
        }
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'ReplayButton'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        Audio_Record_Replay = 1;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_0: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        Audio_Full_Record = CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0));
        if(Audio_Thread_Exist == 1)
          Audio_Thread_Terminate = 1;
        MoveToAudioWindow(pMsg->hWin);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_PRE_PAINT:
    GUI_MULTIBUF_Begin();
      break;
  case WM_POST_PAINT:
    GUI_MULTIBUF_End();
      break;
  case WM_TIMER:
    if(Audio_Record_Ready == 1)
    {
      Audio_Record_Ready = 0;
      hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
      BUTTON_SetText(hItem, "Record");
      BUTTON_SetTextColor(hItem, 0, GUI_BLACK);
      WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2));       // 开启 replay 按键
      WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0));
    }

    if(Audio_Record_OnOff)        // 只有在开启音调提取后才会重启 timer
    {
      #ifdef CMSIS_V1
      WM_RestartTimer(pMsg->Data.v, 1000);
      #endif

      #ifdef CMSIS_V2
      WM_RestartTimer(pMsg->Data.v, 200000000);
      #endif
    }
    else
      WM_DeleteTimer(pMsg->Data.v);
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateAudioWindow
*/
WM_HWIN CreateAudioWindow(void);
WM_HWIN CreateAudioWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
void MoveToAudioWindow(WM_HWIN hWin)
{
  WM_EnableWindow(WM_GetDialogItem(hWin, ID_BUTTON_0));
  WM_DisableWindow(WM_GetDialogItem(hWin, ID_BUTTON_1));
  WM_DisableWindow(WM_GetDialogItem(hWin, ID_BUTTON_2));
}
// USER END

/*************************** End of file ****************************/
