/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_LISTWHEEL_0 (GUI_ID_USER + 0x01)
#define ID_LISTWHEEL_1 (GUI_ID_USER + 0x02)
#define ID_LISTWHEEL_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_0 (GUI_ID_USER + 0x04)


// USER START (Optionally insert additional defines)
static char *_apMonth[] = {
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
};

static char *_apDay[] = {
  "01", "02", "03", "04",
  "05", "06", "07", "08",
  "09", "10", "11", "12",
  "13", "14", "15", "16",
  "17", "18", "19", "20",
  "21", "22", "23", "24",
  "25", "26", "27", "28",
  "29", "30", "31",
};

static char *_apYear[] = {
  "1990","1991", "1992", "1993", "1994", "1995", "1996",
  "1997", "1998", "1999", "2000", "2001", "2002", "2003",
  "2004", "2005", "2006", "2007", "2008", "2009", "2010",
  "2011", "2012", "2013", "2014", "2015", "2016", "2017",
  "2018", "2019", "2020",
};
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern WM_HWIN CreateWindow_Self();
extern GUI_HWIN hCurrentWindow;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "ClockWindow", ID_WINDOW_0, 0, 0, 480, 242, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "ListwheelMon", ID_LISTWHEEL_0, 10, 40, 100, 178, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "ListwheelDay", ID_LISTWHEEL_1, 120, 40, 40, 178, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "ListwheelYear", ID_LISTWHEEL_2, 170, 39, 60, 178, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 75, 14, 80, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static int _OwnerDraw(const WIDGET_ITEM_DRAW_INFO * pDrawItemInfo)
{
  GUI_RECT aRect;

  switch (pDrawItemInfo->Cmd) {
  case WIDGET_ITEM_DRAW_OVERLAY:
    aRect.x0 = pDrawItemInfo->x0;
    aRect.x1 = pDrawItemInfo->x1;
    aRect.y1 = pDrawItemInfo->y1;
    GUI_SetColor(GUI_GRAY_E7);
    GUI_DrawLine(aRect.x0, (aRect.y1-19-16)/2, aRect.x1, (aRect.y1-19-16)/2);
    GUI_DrawLine(aRect.x0, (aRect.y1+19+16)/2, aRect.x1, (aRect.y1+19+16)/2);
    break;
  default:
    return LISTWHEEL_OwnerDraw(pDrawItemInfo);
  }
  return 0;
}


// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "Set Date");
    TEXT_SetFont(hItem, GUI_FONT_13HB_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x008000FF));
    // USER START (Optionally insert additional code for further widget initialization)
    for (int i = 0; i < 3; i++)
    {
      hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0 + i);
      LISTWHEEL_SetLineHeight(hItem, 34);
      LISTWHEEL_SetSnapPosition(hItem, (178 - 34) / 2);
      LISTWHEEL_SetFont(hItem, GUI_FONT_16B_ASCII);
      LISTWHEEL_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
      LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_UNSEL, 0x191919);
      LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x007dfe);
      LISTWHEEL_SetDeceleration(hItem, 35);
      LISTWHEEL_SetOwnerDraw(hItem, _OwnerDraw);
      LISTWHEEL_SetSel(hItem, 0);
    }

    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
    for (int i = 0; i < GUI_COUNTOF(_apMonth); i++)
      LISTWHEEL_AddString(hItem, *(_apMonth + i));
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
    for (int i = 0; i < GUI_COUNTOF(_apDay); i++)
      LISTWHEEL_AddString(hItem, *(_apDay + i));
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
    for (int i = 0; i < GUI_COUNTOF(_apYear); i++)
      LISTWHEEL_AddString(hItem, *(_apYear + i));
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTWHEEL_0: // Notifications sent by 'ListwheelMon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
        LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x191919);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
        LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x007dfe);
        U8 index = LISTWHEEL_GetPos(hItem);
        LISTWHEEL_SetSel(hItem, index);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_1: // Notifications sent by 'ListwheelDay'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
        LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x191919);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
        LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x007dfe);
        U8 index = LISTWHEEL_GetPos(hItem);
        LISTWHEEL_SetSel(hItem, index);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_2: // Notifications sent by 'ListwheelYear'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
        LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x191919);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
        LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x007dfe);
        U8 index = LISTWHEEL_GetPos(hItem);
        LISTWHEEL_SetSel(hItem, index);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateClockWindow
*/
WM_HWIN CreateClockWindow(void);
WM_HWIN CreateClockWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
