/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <string.h>
#include "os_threads.h"
#include "gui_resources.h"
#include "dialog_window.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_LISTVIEW_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_0 (GUI_ID_USER + 0x02)
#define ID_BUTTON_1 (GUI_ID_USER + 0x03)
#define ID_BUTTON_2 (GUI_ID_USER + 0x04)
#define ID_BUTTON_3 (GUI_ID_USER + 0x05)
#define ID_BUTTON_4 (GUI_ID_USER + 0x06)
#define ID_SLIDER_0 (GUI_ID_USER + 0x07)
#define ID_TEXT_0 (GUI_ID_USER + 0x08)
#define ID_TEXT_1 (GUI_ID_USER + 0x09)
#define ID_TEXT_2 (GUI_ID_USER + 0x0A)
#define ID_TEXT_3 (GUI_ID_USER + 0x0B)
#define ID_TEXT_4 (GUI_ID_USER + 0x0C)
#define ID_TEXT_5 (GUI_ID_USER + 0x0D)
#define ID_TEXT_6 (GUI_ID_USER + 0x0E)
#define ID_SLIDER_1 (GUI_ID_USER + 0x0F)
#define ID_TEXT_7 (GUI_ID_USER + 0x10)
#define ID_BUTTON_5 (GUI_ID_USER + 0x11)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern WM_HWIN CreateFileDialog(void);
static void PlayButtonEventHandler(WM_MESSAGE * pMsg);
static void NextButtonEventHandler();
static void TimerCallbackHandler(WM_MESSAGE * pMsg);
static void SliderCallbackHandler(WM_MESSAGE * pMsg);
static void PaintEventHandler();
static void DrawSpectrum(uint16_t x, uint16_t y);

WM_HWIN hListView;

extern U16             Music_Play_Start;            // 音乐开始标志
extern U16             Music_Play_On;               // 音乐播放中标志
extern U16             Music_Thread_Exist;          // 音乐后台线程运行标志

extern uint32_t        uiMusicCurrentMinute;       // 音乐播放进度——分钟
extern uint32_t        uiMusicCurrentSecond;       // 音乐播放进度——秒
extern uint32_t        uiMusicCurrentProgress;     // 音乐播放进度——百分比
extern uint32_t        uiMusicVolumeN;             // 音量系数——分子
extern uint32_t        uiMusicVolumeD;             // 音量系数——分母
extern uint16_t        usWavCacheInvalid;          // wav 文件缓存失效标志
extern uint32_t        uiWavPlayIndex, uiWavSampleRate, uiWavSampleDepth, uiWavChannelNum, uiWavDataLength;

extern uint16_t        Music_FFT_Ready;             // FFT 数据准备完成标志

extern char            AlarmSongPath[128];          // 闹钟歌曲路径

U16                    Music_Item_Current = 0;
char                   musicPath[100];
static uint16_t        sliderClicked = 0;
static uint16_t        Timer_Exist = 0;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "MusicWindow", ID_WINDOW_0, 0, 0, 480, 242, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 255, 0, 220, 160, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "FileButton", ID_BUTTON_0, 315, 195, 50, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "PlayButton", ID_BUTTON_1, 10, 196, 40, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "PauseButton", ID_BUTTON_2, 60, 196, 60, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "NextButton", ID_BUTTON_3, 130, 195, 40, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "DelButton", ID_BUTTON_4, 375, 195, 50, 40, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 12, 168, 400, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ProgText", ID_TEXT_0, 420, 166, 47, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "SongText", ID_TEXT_1, 73, 140, 181, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "bSongText", ID_TEXT_2, 15, 140, 56, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text0", ID_TEXT_3, 10, 132, 20, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text1", ID_TEXT_4, 80, 132, 20, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text2", ID_TEXT_5, 150, 132, 20, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text3", ID_TEXT_6, 220, 132, 20, 15, 0, 0x64, 0 },
  { SLIDER_CreateIndirect, "VolumeSlider", ID_SLIDER_1, 198, 192, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "VolumeText", ID_TEXT_7, 196, 212, 105, 20, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "AlarmButton", ID_BUTTON_5, 435, 195, 40, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  static char tmpBuf[128];
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'MusicWindow'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00E6F48E));
    //
    // Initialization of 'Listview'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
    LISTVIEW_AddColumn(hItem, 165, "Track", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 50, "Duration", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_SetRowHeight(hItem, 20);
    LISTVIEW_SetAutoScrollV(hItem, 1);
    //
    // Initialization of 'FileButton'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "Add");
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'PlayButton'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    BUTTON_SetText(hItem, "Play");
    //
    // Initialization of 'PauseButton'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    BUTTON_SetText(hItem, "Pause");
    //
    // Initialization of 'NextButton'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    BUTTON_SetText(hItem, "Next");
    //
    // Initialization of 'DelButton'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    BUTTON_SetText(hItem, "Del");
    //
    // Initialization of 'ProgText'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x008000FF));
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    TEXT_SetText(hItem, "00:00");
    //
    // Initialization of 'SongText'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "null");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF00FF));
    //
    // Initialization of 'bSongText'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetText(hItem, "Playing: ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF0000));
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Text0'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetText(hItem, "0");
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x0070C76B));
    //
    // Initialization of 'Text1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetText(hItem, "2k");
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00378E37));
    //
    // Initialization of 'Text2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetText(hItem, "4k");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00316B2E));
    //
    // Initialization of 'Text3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetText(hItem, "6k");
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00235023));
    //
    // Initialization of 'VolumeText'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF8000));
    TEXT_SetText(hItem, "10   Volume  100");
    //
    // Initialization of 'AlarmButton'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetText(hItem, "");
    // USER START (Optionally insert additional code for further widget initialization)
    hListView = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
    LISTVIEW_SetGridVis(hListView, 1);
    LISTVIEW_SetAutoScrollV(hListView, 1);
    LISTVIEW_SetBkColor(hListView, LISTVIEW_CI_UNSEL, GUI_WHITE);
    LISTVIEW_SetTextColor(hListView, LISTVIEW_CI_UNSEL, GUI_LIGHTBLUE);
    LISTVIEW_SetBkColor(hListView, LISTVIEW_CI_SEL, GUI_LIGHTBLUE);
    LISTVIEW_SetTextColor(hListView, LISTVIEW_CI_SEL, GUI_WHITE);
    LISTVIEW_SetRowHeight(hListView, 20);
    LISTVIEW_SetBkColor(hListView, LISTVIEW_CI_SELFOCUS, GUI_LIGHTBLUE);
    LISTVIEW_SetTextColor(hListView, LISTVIEW_CI_SELFOCUS, GUI_WHITE);
    LISTVIEW_DeleteAllRows(hListView);
    LISTVIEW_SetFont(hListView, GUI_FONT_13B_ASCII);
    LISTVIEW_SetDefaultFont(GUI_FONT_13B_ASCII);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_None);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetBitmap(hItem, 0, &bmAlarmSmall);
    //

    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
    SLIDER_SetRange(hItem, 0, 100);
    SLIDER_SetNumTicks(hItem, 100);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
    SLIDER_SetRange(hItem, 10, 100);
    SLIDER_SetNumTicks(hItem, 9);
    SLIDER_SetValue(hItem, 50);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTVIEW_0: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'FileButton'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        CreateFileDialog();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'PlayButton'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        PlayButtonEventHandler(pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'PauseButton'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        Music_Play_On = 0;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'NextButton'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        NextButtonEventHandler();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'DelButton'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        if(LISTVIEW_GetSel(hListView) != Music_Item_Current)    // 默认无法删除当前播放音乐
          LISTVIEW_DeleteRow(hListView, LISTVIEW_GetSel(hListView));
        else
          CreateAlarmDialog_Self("Invalid Operation", "Can't delete a song\n while it's playing", DIALOG_NOTHING);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        sliderClicked = 1;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        sliderClicked = 0;
        SliderCallbackHandler(pMsg);
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_1: // Notifications sent by 'VolumeSlider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        uiMusicVolumeN = SLIDER_GetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1));
        if(uiMusicVolumeN > 50)
          uiMusicVolumeN = (uiMusicVolumeN - 50) * 4 + 50;
        uiMusicVolumeD = 50;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'AlarmButton'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        if(LISTVIEW_GetNumRows(hListView) != 0)
        {
          LISTVIEW_GetItemText(hListView, 0, Music_Item_Current, musicPath, 100);
          strcpy(AlarmSongPath, musicPath);
          sprintf(tmpBuf, "Successfully set \n `%s`\n as the alarm sound", AlarmSongPath);
          CreateAlarmDialog_Self("Success", tmpBuf, DIALOG_NOTHING);
        }
        else
          CreateAlarmDialog_Self("Failed", "There's no song \nin the list", DIALOG_NOTHING);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_TIMER:
    TimerCallbackHandler(pMsg);
    break;
  case WM_PRE_PAINT:
    GUI_MULTIBUF_Begin();
    break;
  case WM_PAINT:
    PaintEventHandler();
    break;
  case WM_POST_PAINT:
    GUI_MULTIBUF_End();
    break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMusicWindow
*/
WM_HWIN CreateMusicWindow(void);
WM_HWIN CreateMusicWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
void MoveToMusicWindow(WM_HWIN hWin)
{
  uiMusicVolumeN = SLIDER_GetValue(WM_GetDialogItem(hWin, ID_SLIDER_1));
  if (uiMusicVolumeN > 50)
    uiMusicVolumeN = (uiMusicVolumeN - 50) * 4 + 50;
  uiMusicVolumeD = 50;
}


/**
 * @brief  Play 按键的回调函数
 * @param  WM_MESSAGE * pMsg
 * @retval None
 */
void MusicWindowPlayButtonHit(WM_HWIN hWin);
static void PlayButtonEventHandler(WM_MESSAGE * pMsg)
{
  MusicWindowPlayButtonHit(pMsg->hWin);
}

void MusicWindowPlayButtonHit(WM_HWIN hWin)
{
  if (LISTVIEW_GetNumRows(hListView) > 0)
  {
    Music_Item_Current = LISTVIEW_GetSel(hListView);
    if (Music_Item_Current == 0xffff)     // 未选中任何 row
      Music_Item_Current = 0;             // 默认播放第一个文件

    LISTVIEW_SetSel(hListView, Music_Item_Current);

    LISTVIEW_GetItemText(hListView, 0, Music_Item_Current, musicPath, 100);     // 获取文件全路径

    Music_Play_Start = 1;         // 置位播放标志
    vMusicTaskCreate();         // 启动音乐线程
    if(!Timer_Exist){
      Timer_Exist = 1;
      WM_CreateTimer(hWin, 0, 1000, 0);
    }
  }
}


/**
 * @brief  Next 按键的回调函数
 * @param  None
 * @retval None
 */
static void NextButtonEventHandler()
{
  if (LISTVIEW_GetNumRows(hListView) > 0)
  {
    Music_Item_Current = (Music_Item_Current + 1) % LISTVIEW_GetNumRows(hListView);
    LISTVIEW_GetItemText(hListView, 0, Music_Item_Current, musicPath, 100);
    Music_Play_Start = 1;
    LISTVIEW_SetSel(hListView, Music_Item_Current);
  }
}



/**
 * @brief  滑块的回调函数
 * @param  WM_MESSAGE * pMsg
 * @retval None
 */
static void SliderCallbackHandler(WM_MESSAGE * pMsg)
{
  uint32_t      sliderVal;

  sliderVal = SLIDER_GetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0));
  uiWavPlayIndex = sliderVal * uiWavDataLength / 100;

  usWavCacheInvalid = 1;
}



/**
 * @brief  定时器的回调函数
 * @param  WM_MESSAGE * pMsg
 * @retval None
 */
static void TimerCallbackHandler(WM_MESSAGE * pMsg)
{
  static WM_HWIN       hItem;
  static char          charBuffer[32];
  static short         i, j;
  static uint16_t      secondCount = 0;
  static uint16_t      msCount = 0;
  static const  GUI_RECT DrawingRect = {0, 0, 252, 130};

  msCount += 20;
  if(Music_FFT_Ready)
    WM_InvalidateRect(pMsg->hWin, &DrawingRect);

  if(msCount >= 200)
  {
    msCount = 0;
    secondCount++;

    uiMusicCurrentSecond = uiWavPlayIndex / uiWavChannelNum / uiWavSampleRate / (uiWavSampleDepth / 8) % 60;
    uiMusicCurrentMinute = uiWavPlayIndex / uiWavChannelNum / uiWavSampleRate / (uiWavSampleDepth / 8) / 60;
    uiMusicCurrentProgress = uiWavPlayIndex * 100 / uiWavDataLength;

    sprintf(charBuffer, "%02d:%02d", uiMusicCurrentMinute, uiMusicCurrentSecond);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, charBuffer);

    if(sliderClicked == 0)
      SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0), uiMusicCurrentProgress);
    
    if(secondCount % 5 == 0)
      LISTVIEW_SetSel(hListView, Music_Item_Current);

    LISTVIEW_GetItemText(hListView, 0, Music_Item_Current, charBuffer, 32);
    for (i = strlen(charBuffer) - 1; i > -1; i--)
      if (charBuffer[i] == '/')
        break;
    for (j = 0, i++; charBuffer[i] != '.';)
      charBuffer[j++] = charBuffer[i++];
    charBuffer[j] = '\0';
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, charBuffer);
  }

  if(Music_Thread_Exist){
#ifdef CMSIS_V1
    WM_RestartTimer(pMsg->Data.v, 20);
#endif

#ifdef CMSIS_V2
    WM_RestartTimer(pMsg->Data.v, 1000000);
#endif
  }
  else
  {
    WM_DeleteTimer(pMsg->Data.v);
    Timer_Exist = 0;
  }
}



/**
 * @brief  处理 WM_PAINT 事件
 * @param  None
 * @retval None
 */
static void PaintEventHandler()
{
  if (Music_FFT_Ready)
  {
    GUI_Clear();
    GUI_SetColor(GUI_WHITE);
    GUI_DrawRoundedFrame(8, 2, 248, 136, 3, 2);    
    DrawSpectrum(12, 6 + 128 - 128);

    Music_FFT_Ready = 0;
  }
}



/**
 * @brief  频谱显示
 * @param  uint16_t x   频谱x坐标
 * @param  uint16_t y   频谱y坐标
 * @retval None
 */
static void DrawSpectrum(uint16_t x, uint16_t y)
{
  static uint16_t       topValueArr[32] = {0}; /* 频谱顶值表 */
  static uint16_t       curValueArr[32] = {0}; /* 频谱当前值表 */
  static uint8_t        timeArr[32] = {0};      /* 顶值停留时间表 */
  static const uint16_t maxVal = 128;     /* 高度固定为128个像素 */
  static uint16_t       i, temp, deltaX = 7;

  extern float32_t       fMusic_FFT_Data[];
  extern float32_t       fMusic_FFT_Mag[];


  /* 显示32条频谱 */
  for (i = 0; i < 32; i++)
  {
    temp = (uint16_t)(fMusic_FFT_Mag[i] / 512);

    /* 2. 更新频谱数值 */
    if (curValueArr[i] < temp)
      curValueArr[i] = temp;
    else
    {
      if (curValueArr[i] > 1)
        curValueArr[i] -= 2;
      else
        curValueArr[i] = 0;
    }

    /* 3. 更新频谱顶值 */
    if (timeArr[i])
      timeArr[i]--;
    else if (topValueArr[i])
      topValueArr[i]--;

    /* 4. 重设频谱顶值 */
    if (curValueArr[i] > topValueArr[i])
    {
      topValueArr[i] = curValueArr[i];
      timeArr[i] = 10; /* 重设峰值停顿时间 */
    }

    /* 5. 防止超出频谱值和顶值范围，高度固定为128个像素 */
    if (curValueArr[i] > maxVal)
      curValueArr[i] = maxVal;

    if (topValueArr[i] > maxVal)
      topValueArr[i] = maxVal;
  }

  /* 6. 绘制得到的频谱 */
  for (i = 0; i < 32; i++)
  {
    /* 显示频谱 */
    GUI_DrawGradientV(x,
                      y + maxVal - curValueArr[i],
                      x + deltaX,
                      y + maxVal,
                      GUI_BLUE,
                      GUI_BLUE);

    /* 显示顶值 */
    GUI_SetColor(GUI_DARKGREEN);
    GUI_DrawHLine(y + maxVal - topValueArr[i] - 1, x, x + deltaX);
    GUI_SetColor(GUI_DARKGREEN);
    GUI_DrawHLine(y + maxVal - topValueArr[i] - 1, x, x + deltaX);
    x += deltaX;
  }
}
// USER END

/*************************** End of file ****************************/
