/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "resources.h"
#include "os_time.h"
#include "os_state.h"
//#undef GUI_ID_USER
//#define GUI_ID_USER (0x800+0x10)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_BUTTON_0     (GUI_ID_USER + 0x01)
#define ID_TEXT_0     (GUI_ID_USER + 0x02)
#define ID_PROGBAR_0     (GUI_ID_USER + 0x03)
#define ID_PROGBAR_1     (GUI_ID_USER + 0x04)


// USER START (Optionally insert additional defines)
//#define GUI_ID_USER 0x800
void updateTaskBarTitle();
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
char taskBarTitle[] = "10/11/2021  09:48:00 Mon    Group4  @MianXu @WangHe";
char taskBarSuffix[] = "    Group4  @MianXu @WangHe";

extern GUI_HWIN hCurrentWindow;
extern GUI_HWIN hHomeWindow;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "TaskBar", ID_WINDOW_0, 0, 0, 480, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_0, 450, 0, 30, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Title", ID_TEXT_0, 0, 0, 390, 30, 0, 0x64, 0 },
  { PROGBAR_CreateIndirect, "CPU", ID_PROGBAR_0, 410, 0, 40, 30, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Memory", ID_PROGBAR_1, 370, 0, 40, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  GUI_RECT  Rect;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'TaskBar'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00AEAEAE));
    //
    // Initialization of ''
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_13B_ASCII);
    //
    // Initialization of 'Title'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, " ");
    // USER START (Optionally insert additional code for further widget initialization)
    hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
    PROGBAR_SetValue(hItem, 100);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by ''
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        //GUI_EndDialog(hCurrentWindow, 0);
        //hCurrentWindow = CreateWindow_Self();
        WM_BringToBottom(hCurrentWindow);
        WM_BringToTop(hCurrentWindow = hHomeWindow);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_PAINT:
    WM_GetClientRect(&Rect);
    GUI_ClearRectEx(&Rect);
    GUI_DrawRectEx(&Rect);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextColor(hItem, GUI_YELLOW);
    TEXT_SetFont(hItem, &GUI_Font16B_ASCII);
    TEXT_SetText(hItem, taskBarTitle);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
    if(osGetCPUUsage() > 60)
      PROGBAR_SetBarColor(hItem, 0, GUI_RED);
    else
      PROGBAR_SetBarColor(hItem, 0, GUI_GREEN);
    PROGBAR_SetValue(hItem, osGetCPUUsage());
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_1);
    if(osGetMemUsage() > 60)
      PROGBAR_SetBarColor(hItem, 0, GUI_RED);
    else
      PROGBAR_SetBarColor(hItem, 0, GUI_GREEN);
    PROGBAR_SetValue(hItem, osGetMemUsage());
  break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateTaskBar
*/
WM_HWIN CreateTaskBar(void);
WM_HWIN CreateTaskBar(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
WM_HWIN CreateTaskBar_Self(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);

  WM_HWIN hButtonClock = WM_GetDialogItem(hWin, ID_BUTTON_0);
  BUTTON_SetBitmap(hButtonClock, 0, &bmHome);
  return hWin;
}


void updateTaskBarTitle()
{
  extern int time_second; 
  extern int time_minute;
  extern int time_hour;
  extern int date_day;
  extern int date_month;
  extern int date_year;
  extern char date_weekday[3];

  sprintf(taskBarTitle, "%02d/%02d/%d  %02d:%02d:%02d %s%s",
            date_month, date_day, date_year, time_hour, time_minute, time_second, date_weekday, taskBarSuffix);
}
// USER END

/*************************** End of file ****************************/
