/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "gui_resources.h"
#include "os_time.h"
#include "os_state.h"
#include "os_threads.h"
#include "app_alarm.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_0 (GUI_ID_USER + 0x02)
#define ID_PROGBAR_0 (GUI_ID_USER + 0x03)
#define ID_PROGBAR_1 (GUI_ID_USER + 0x04)
#define ID_IMAGE_0 (GUI_ID_USER + 0x05)
#define ID_IMAGE_1 (GUI_ID_USER + 0x06)


// USER START (Optionally insert additional defines)
static void updateTaskBar(WM_HWIN hWin);
static void updateTaskBarAlarmState(WM_HWIN hAlarmImage);
static void updateTaskBarMusicState(WM_HWIN hMusicImage);
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
char taskBarTitle[50] = "10/11/2021  09:48:00 Mon";

extern uint16_t        Audio_Record_Replay;
extern U16             Music_Play_On;              // 音乐播放中标志
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "TaskBar", ID_WINDOW_0, 0, 0, 480, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_0, 450, 0, 30, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Title", ID_TEXT_0, 0, 0, 200, 30, 0, 0x64, 0 },
  { PROGBAR_CreateIndirect, "CPU", ID_PROGBAR_0, 405, 0, 40, 30, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Memory", ID_PROGBAR_1, 360, 0, 40, 30, 0, 0x0, 0 },
  { IMAGE_CreateIndirect, "Image1", ID_IMAGE_0, 280, -1, 30, 30, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Image2", ID_IMAGE_1, 310, 1, 30, 30, 0, 0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'TaskBar'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0xFFFFFFFF));
    //
    // Initialization of ''
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_13B_ASCII);
    //
    // Initialization of 'Title'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, " ");
    // USER START (Optionally insert additional code for further widget initialization)
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetBitmap(hItem, 0, &bmHome);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
    IMAGE_SetBitmap(hItem, &bmAlarm_disable);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
    IMAGE_SetBitmap(hItem, &bmMusic_disable);

    #ifdef CMSIS_V1
    WM_CreateTimer(pMsg->hWin, 0, 100, 0);
    #endif

    #ifdef CMSIS_V2
    WM_CreateTimer(pMsg->hWin, 0, 200000, 0);
    #endif

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextColor(hItem, GUI_BLUE);
    TEXT_SetFont(hItem, &GUI_Font16B_ASCII);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by ''
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_BringToBottom(hCurrentWindow);
        WM_BringToTop(hCurrentWindow = hHomeWindow);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_TIMER:
    updateTaskBar(pMsg->hWin);
    #ifdef CMSIS_V1
    WM_RestartTimer(pMsg->Data.v, 1000);
    #endif


    #ifdef CMSIS_V2
    WM_RestartTimer(pMsg->Data.v, 200000000);
    #endif
    break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateTaskBar
*/
WM_HWIN CreateTaskBar(void);
WM_HWIN CreateTaskBar(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
static void updateTaskBar(WM_HWIN hWin)
{
  WM_HWIN hItem;

  // 更新日期时间栏
  sprintf(taskBarTitle, "%02d/%02d/%d  %02d:%02d:%02d %s",
            os_date_month, os_date_day, os_date_year, os_time_hour, os_time_minute, os_time_second, os_date_weekday);
  hItem = WM_GetDialogItem(hWin, ID_TEXT_0);
  TEXT_SetText(hItem, taskBarTitle);

  updateTaskBarAlarmState(WM_GetDialogItem(hWin, ID_IMAGE_0));
  updateTaskBarMusicState(WM_GetDialogItem(hWin, ID_IMAGE_1));

  hItem = WM_GetDialogItem(hWin, ID_PROGBAR_0);
  PROGBAR_SetValue(hItem, osGetCPUUsage());

  hItem = WM_GetDialogItem(hWin, ID_PROGBAR_1);
  PROGBAR_SetValue(hItem, osGetMemUsage());
}


/**
 * @brief  update the alarm state image of taskbar
 * @param  WM_HWIN hItem
 * @retval None
 */
static void updateTaskBarAlarmState(WM_HWIN hAlarmImage)
{
	static uint8_t		alarmState = 0;

	if (alarmState != alarm_enabled)
	{
		alarmState = alarm_enabled;
		if (alarmState == 1)
			IMAGE_SetBitmap(hAlarmImage, &bmAlarm_enable);
		else
			IMAGE_SetBitmap(hAlarmImage, &bmAlarm_disable);
	}
}


/**
 * @brief  update the music state image of taskbar
 * @param  WM_HWIN hItem
 * @retval None
 */
static void updateTaskBarMusicState(WM_HWIN hMusicImage)
{
	static uint8_t		musicState = 0;

	if (musicState != Audio_Record_Replay | Music_Play_On)
	{
		musicState = Audio_Record_Replay | Music_Play_On;
		if (musicState == 1)
			IMAGE_SetBitmap(hMusicImage, &bmMusic_enable);
		else
			IMAGE_SetBitmap(hMusicImage, &bmMusic_disable);
	}
}
// USER END

/*************************** End of file ****************************/
